###########################
# Configuration for rubocop
# in .rubocop.yml

##############
# Global rules
# see .rubocop_common.yml

##############
# Inherit default rules first, and then override those rules with
# our violation whitelist.
inherit_from:
  - .rubocop_common.yml
  - .rubocop_todo.yml

##############
# Project specific overrides here, example:
# Metrics/BlockLength:
#   Exclude:
#    - 'tasks/the_huge_task.rake'

AllCops:
  Exclude:
    - phobos_db_checkpoint.gemspec
    - spec/setup/**/*.rb

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 17
