sudo: required
language: ruby
rvm:
  - 2.4.1

services:
  - docker

before_install:
  - env
  - docker-compose --version
  - docker --version
  - docker-compose config
  - docker-compose build test

script:
  - docker-compose run --rm test rspec
