version: '2'
services:
  test:
    depends_on:
      - db
    build:
      context: .
    command: rspec
    volumes:
      - ./coverage:/opt/phobos_db_checkpoint/coverage
    network_mode: service:db

  db:
    image: postgres:9.5-alpine
    ports:
     - 5432:5432
